AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda ETL function, pulls data from SFTP to S3 to RDS.
Globals:
  Function:
    Tags:
      oml-cost-center: 10016477
      oml-application-name: RBA Group Compliance
      oml-application-id: RBA Group Compliance
      oml-department: Applied Intelligence AI
      oml-environment: Non Prod
      oml-project-name: RBA Group Compliance
      oml-resource-owner-team: Applied Intelligence AI
      oml-resource-owner-team-email: KAmritlallatoldmutual.com
      oml-resource-owner-contact: KAmritlallatoldmutual.com
      oml-business-owner: Kusheel Amritlall
Resources:
  SFTPToS3RDSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - x86_64
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      CodeUri: SFTPToS3RDSLambdaFunction
      Environment:
        Variables:
          AWS_SM_SECRET_NAME: oml-cs-ai-non-prod-compliance-secrets
          AWS_STS_SERVICE_END_POINT: sts.ap-south-1.amazonaws.com
          ROLE_ARN: arn:aws:iam::713528111139:role/iam-S3-lambda-role-personal
          ROLE_SESSION_NAME: GroupComplianceSFTPRDSIngestion
          STAGE: DEV
      FunctionName: SFTPToS3RDSLambdaFunction
      Handler: com.om.gc.S3FilePutTriggerLambda::handleRequest
      MemorySize: 512
      Role: arn:aws:iam::713528111139:role/iam-S3-lambda-role-personal
      Runtime: java8
      Timeout: 900
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.SFTPToS3RDSLambdaFunctioned6171ceDepLayer
    Metadata:
      SamResourceId: SFTPToS3RDSLambdaFunction
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /home/pp/git/Group_Compliance/SFTP-to-S3-lambda/.aws-sam/auto-dependency-layer/nested_template.yaml
    Type: AWS::CloudFormation::Stack
