version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Compiling Java code..."
      - cd SFTP-to-S3-lambda
      - mvn clean
      - mvn compile
      - echo "Build completed successfully!"
  post_build:
    commands:
      - echo "Uploading JAR to S3..."
      - aws s3 cp SFTP-to-S3-lambda/target/S3FilePutTriggerLambda.jar s3://codepipeline-ap-south-1-538590669851/S3FilePutTriggerLambda.jar
      - echo "Upload completed successfully!"