AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "AWS Lambda ETL function, pulls data from SFTP to S3 to RDS."

Globals:
  Function:
    Tags:
      oml-cost-center: 10065369
      oml-application-name: Group Compliance DCC
      oml-application-id: Group Compliance DCC
      oml-department: Group Compliance
      oml-environment: Non Prod
      oml-project-name: Group Compliance DCC
      oml-resource-owner-team: Group Compliance
      oml-resource-owner-team-email: leezaamlatoldmutual.com
      oml-resource-owner-contact: leezaamlatoldmutual.com
      oml-business-owner: Leezaam Leitch

Resources:
  SFTPToS3RDSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      #CodeUri: /home/pp/git/Group_Compliance/SFTP-to-S3-lambda
      #CodeUri: s3://oml-cs-ai-non-prod-compliance/code/SFTP-to-S3-lambda-1.0-SNAPSHOT-v2.jar
      Code:
        S3Bucket: oml-cs-ai-non-prod-compliance
        S3Key: 'code/SFTP-to-S3-lambda-1.0-SNAPSHOT-v2.jar'
      Environment:
        Variables:
          AWS_SM_SECRET_NAME: oml-cs-ai-non-prod-compliance-secrets
          AWS_STS_SERVICE_END_POINT: sts.eu-west-1.amazonaws.com
          ROLE_ARN: arn:aws:iam::332760374405:role/customer_om_cs-ai-groupcompliance-nonprod-lambda-execution-role

          ROLE_SESSION_NAME: GroupComplianceSFTPRDSIngestion
          STAGE: DEV

      FunctionName: SFTPToS3RDSLambdaFunction
      Handler: com.om.gc.S3FilePutTriggerLambda::handleRequest
      MemorySize: 512
      Role: arn:aws:iam::332760374405:role/customer_om_cs-ai-groupcompliance-nonprod-lambda-execution-role
      Runtime: java8
      Timeout: 900

